var education = ["SSC","HSC","BCS","BS","BCOM","MS","M.Phill","PhD"];
document.write("Qualifications: " +"<br>")
document.write("<br>" + "1) " + education[0])
document.write("<br>" + "2) " + education[1])
document.write("<br>" + "3) " + education[2])
document.write("<br>" + "4) " + education[3])
document.write("<br>" + "5) " + education[4])
document.write("<br>" + "6) " + education[5])
document.write("<br>" + "7) " + education[6])
document.write("<br>" + "8) " + education[7])